### ISSUE TITLE
pip install fails with IOError: [Errno 2] No such file or directory: '/tmp/pip-build-375pra/misu/README.md'

### ISSUE THREAD

**Issue by nbeaver** [cjrh/misu#7]
Command:

```
pip install --user misu
```

Full backtrace:

```
------------------------------------------------------------
/usr/bin/pip run on Wed Jan 27 21:10:20 2016
Downloading/unpacking misu
  Getting page https://pypi.python.org/simple/misu/
  URLs to search for versions for misu:
  * https://pypi.python.org/simple/misu/
  Analyzing links from page https://pypi.python.org/simple/misu/
    Skipping https://pypi.python.org/packages/2.7/m/misu/misu-1.0.2-cp27-none-macosx_10_5_x86_64.whl#md5=e4c2a2acc546f1ca989c33f7493b85b7 (from https://pypi.python.org/simple/misu/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/2.7/m/misu/misu-1.0.2-cp27-none-win_amd64.whl#md5=537649c340b1ea74208def1bd26e6d1f (from https://pypi.python.org/simple/misu/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/3.4/m/misu/misu-1.0.2-cp34-cp34m-macosx_10_5_x86_64.whl#md5=04b292471e04b0b13685b8d0806f5351 (from https://pypi.python.org/simple/misu/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/3.4/m/misu/misu-1.0.2-cp34-none-win_amd64.whl#md5=cb74f896e9168ff2dbf22269b1ccb925 (from https://pypi.python.org/simple/misu/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/m/misu/misu-0.1.0-cp27-none-macosx_10_5_x86_64.whl#md5=0f0fb93b9a0f034316c05dc60a1b411c (from https://pypi.python.org/simple/misu/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp27/m/misu/misu-0.1.0-cp27-none-win_amd64.whl#md5=02603beb73e7fe5d2d84ed0e1bce6e1b (from https://pypi.python.org/simple/misu/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp34/m/misu/misu-0.1.0-cp34-cp34m-macosx_10_5_x86_64.whl#md5=e9534068d1de93be2907e83d3a8b364e (from https://pypi.python.org/simple/misu/) because it is not compatible with this Python
    Found link https://pypi.python.org/packages/source/m/misu/misu-1.0.2.tar.gz#md5=363e4b3701e025f362f6369b61953b24 (from https://pypi.python.org/simple/misu/), version: 1.0.2
  Downloading from URL https://pypi.python.org/packages/source/m/misu/misu-1.0.2.tar.gz#md5=363e4b3701e025f362f6369b61953b24 (from https://pypi.python.org/simple/misu/)
  Running setup.py (path:/tmp/pip-build-375pra/misu/setup.py) egg_info for package misu
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-375pra/misu/setup.py", line 10, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/lib/python2.7/codecs.py", line 878, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-375pra/misu/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-375pra/misu/setup.py", line 10, in <module>

    with open(path.join(here, 'README.md'), encoding='utf-8') as f:

  File "/usr/lib/python2.7/codecs.py", line 878, in open

    file = __builtin__.open(filename, mode, buffering)

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-375pra/misu/README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-375pra/misu
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-375pra/misu
```

**Comment by cjrh** [comment]
Sorry for leaving this issue so long.  I didn't notice it come it, but I was extremely busy at the time.  It looks like the installation on Linux is not working.  This is not surprising as I haven't tested or tried it at all!   It looks like it tries to install from the source distribution, which means running `setup.py`, which means reading `README.md` to create the `long_description` parameter for the `setup()` function.

Since this issue, I am now using `README.rst` in the `setup.py` instead of the markdown file.  I have also added the two README files to `MANIFEST.in` in 00d70634e7a69df8296653ba00b4c3f79b7e3a3f although this commit is not yet included in a release.  Hopefully I'll be able to make a new release soon.

**Comment by cjrh** [comment]
I need to follow the instructions here: http://docs.cython.org/en/latest/src/reference/compilation.html#distributing-cython-modules

**Comment by cjrh** [comment]
Hmm I got confused. My recent comments above were about installation on Linux, but this issue is really about failure to install because a README wasn't included in the distribution; an issue that has long since been fixed. Closing.
